# -*- coding: utf-8 -*-
"""Kelompok_6_Statistika_Kelas_C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTuljBUn_4toWhW7EEcgGyVYVgHGKX0o
"""

# Import semua library yang dibutuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

print("Library berhasil diimport!")

# Load dataset
df = pd.read_csv('study_performance.csv')

# Filter hanya Group C
groupC = df[df['race_ethnicity'] == 'group C']['math_score'].reset_index(drop=True)

# Random sampling 100 data
# random_state=42 artinya hasil sampelnya SELALU SAMA setiap dijalankan
np.random.seed(42)
sample = groupC.sample(n=100, random_state=42).reset_index(drop=True)

print(f"Total data Group C   : {len(groupC)}")
print(f"Jumlah sampel        : {len(sample)}")
print(f"\nData sampel:")
print(sample.values)

# Statistik Deskriptif
mean   = sample.mean()
median = sample.median()
std    = sample.std(ddof=1)
var    = sample.var(ddof=1)
min_   = sample.min()
max_   = sample.max()
q1     = sample.quantile(0.25)
q3     = sample.quantile(0.75)
iqr    = q3 - q1
skew   = sample.skew()
kurt   = sample.kurt()
cv     = (std / mean) * 100

print("=" * 40)
print("     STATISTIKA DESKRIPTIF")
print("=" * 40)
print(f"Jumlah Data (n)    : {len(sample)}")
print(f"Rata-rata          : {mean:.4f}")
print(f"Median             : {median:.4f}")
print(f"Standar Deviasi    : {std:.4f}")
print(f"Variansi           : {var:.4f}")
print(f"Nilai Minimum      : {min_}")
print(f"Nilai Maksimum     : {max_}")
print(f"Range              : {max_ - min_}")
print(f"Q1                 : {q1}")
print(f"Q3                 : {q3}")
print(f"IQR                : {iqr}")
print(f"Skewness           : {skew:.4f}")
print(f"Kurtosis           : {kurt:.4f}")
print(f"Koefisien Variasi  : {cv:.2f}%")
print("=" * 40)

# ==============================
# VISUALISASI 1 — HISTOGRAM
# ==============================

plt.figure(figsize=(10, 6))

# Plot histogram
sns.histplot(
    sample,
    bins=15,
    kde=True,
    color='steelblue',
    edgecolor='white'
)

# Garis rata-rata
plt.axvline(
    mean,
    color='red',
    linestyle='--',
    linewidth=2,
    label=f'Mean = {mean:.2f}'
)

# Garis median
plt.axvline(
    median,
    color='green',
    linestyle='-.',
    linewidth=2,
    label=f'Median = {median:.2f}'
)

# Label dan judul
plt.title(
    'Histogram Nilai Matematika Siswa Kelompok Etnis C',
    fontsize=14,
    fontweight='bold',
    pad=15
)

plt.xlabel('Nilai Matematika', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)

plt.legend(fontsize=11)

plt.tight_layout()

plt.savefig(
    'histogram.png',
    dpi=150,
    bbox_inches='tight'
)

plt.show()
plt.close()

print("Histogram berhasil disimpan!")

# ==============================
# VISUALISASI 2 — QQ PLOT
# ==============================

plt.figure(figsize=(8, 8))

# QQ Plot
sm.qqplot(sample, line='s', ax=plt.gca(),
          markersize=6, alpha=0.7)

# Judul dan label
plt.title('QQ Plot Nilai Matematika Siswa Kelompok Etnis C',
          fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Theoretical Quantiles', fontsize=12)
plt.ylabel('Sample Quantiles', fontsize=12)
plt.tight_layout()
plt.savefig('qqplot.png', dpi=150, bbox_inches='tight')
plt.show()
plt.close()
print("QQ Plot berhasil disimpan!")

# ==============================
# UJI NORMALITAS KOLMOGOROV-SMIRNOV
# ==============================

ks_stat, ks_pval = stats.kstest(sample, 'norm',
                                 args=(mean, std))
d_tabel = 1.36 / np.sqrt(len(sample))

print("=" * 45)
print("   UJI NORMALITAS KOLMOGOROV-SMIRNOV")
print("=" * 45)
print(f"D hitung        : {ks_stat:.4f}")
print(f"D tabel (α=0.05): {d_tabel:.4f}")
print(f"p-value         : {ks_pval:.4f}")
print("-" * 45)
if ks_pval >= 0.05:
    print("KEPUTUSAN: H0 DITERIMA")
    print("Data BERDISTRIBUSI NORMAL")
else:
    print("KEPUTUSAN: H0 DITOLAK")
    print("Data TIDAK berdistribusi normal")
print("=" * 45)

# ==============================
# ONE SAMPLE T-TEST
# ==============================

mu0    = 65.5
t_stat, t_pval = stats.ttest_1samp(sample, mu0)
t_tabel = stats.t.ppf(0.975, df=len(sample)-1)

print("=" * 45)
print("       ONE SAMPLE T-TEST")
print("=" * 45)
print(f"Rata-rata sampel (x̄) : {mean:.4f}")
print(f"Nilai hipotesis (μ₀)  : {mu0}")
print(f"Standar deviasi (s)   : {std:.4f}")
print(f"n                     : {len(sample)}")
print("-" * 45)
print(f"t hitung              : {t_stat:.4f}")
print(f"t tabel (α/2=0.025)   : {t_tabel:.4f}")
print(f"p-value               : {t_pval:.4f}")
print("-" * 45)
if t_pval >= 0.05:
    print("KEPUTUSAN: H0 DITERIMA")
    print("Tidak terdapat perbedaan signifikan")
else:
    print("KEPUTUSAN: H0 DITOLAK")
    print("Terdapat perbedaan yang signifikan")
print("=" * 45)